title: testTest
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://gygimdev.github.io

aux_links:
  Template Repository: https://github.com/gygimdev/gygimdev.github.io
